GROUP=com.allstask
VERSION_NAME=0.25.0

POM_URL=https://github.com/allstask/allstask-sdks
POM_SCM_URL=git@github.com:allstask/allstask-sdks.git
POM_SCM_CONNECTION=scm:git:git@github.com:allstask/allstask-sdks.git
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:allstask/allstask-sdks.git
POM_LICENCE_NAME=The MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=allstask
POM_DEVELOPER_NAME=Allstask
POM_DEVELOPER_EMAIL=support@allstask.com

POM_DESCRIPTION=Allstask Billing SDK for Java
POM_NAME=allstask
POM_ARTIFACT_ID=allstask
POM_PACKAGING=jar
POM_ORGANIZATION_URL=https://allstask.com

VENDOR_NAME=Allstask (https://allstask.com)
